name: CI/CD Pipeline Complete

on:
  push:
    branches: ["main"]

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/devops-phase4:latest
            ghcr.io/${{ github.repository_owner }}/devops-phase4:v1.0

  deploy-to-server:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "1. Pulling the latest image..."
            docker pull ghcr.io/${{ github.repository_owner }}/devops-phase4:v1.0

            echo "2. Stopping and Removing the old container..."
            docker stop my-live-app || true
            docker rm my-live-app || true

            echo "3. Starting the new container..."
            docker run -d --name my-live-app -p 80:5000 ghcr.io/${{ github.repository_owner }}/devops-phase4:v1.0

            echo "4. Cleanup old hidden images to save space..."
            docker image prune -f
